default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  pool: <%= ENV['DATABASE_POOL'] || 5 %>
  username: <%= ENV['DATABASE_USERNAME'] || 'mentoring' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'mentoring' %>
  database: <%= ENV['DATABASE_NAME'] || 'mentoring' %>
  timeout: 5000

default_replica: &default_replica
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_REPLICA_HOST'] || ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_REPLICA_PORT'] || ENV['DATABASE_PORT'] || 5432 %>
  pool: <%= ENV['DATABASE_REPLICA_POOL'] || ENV['DATABASE_POOL'] || 5 %>
  username: <%= ENV['DATABASE_REPLICA_USERNAME'] || ENV['DATABASE_USERNAME'] || 'mentoring' %>
  password: <%= ENV['DATABASE_REPLICA_PASSWORD'] || ENV['DATABASE_PASSWORD'] || 'mentoring' %>
  database: <%= ENV['DATABASE_REPLICA_NAME'] || ENV['DATABASE_NAME'] || 'mentoring' %>
  timeout: 5000
  replica: true

development:
  master:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'mentoring_development' %>
  replica:
    <<: *default_replica
    database: <%= ENV['DATABASE_NAME'] || 'mentoring_development' %>

test:
  master:
    <<: *default
    database: mentoring_test<%= ENV['TEST_ENV_NUMBER'] %>
  replica:
    <<: *default_replica
    database: mentoring_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  master:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'stagingdatabase' %>
  replica:
    <<: *default_replica
    database: <%= ENV['DATABASE_NAME'] || 'stagingdatabase' %>

new_staging:
  master:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'stagingdatabase' %>
  replica:
    <<: *default_replica
    database: <%= ENV['DATABASE_NAME'] || 'stagingdatabase' %>

production:
  master:
    <<: *default
    variables:
        statement_timeout: 60s
        lock_timeout: 55s
  replica:
    <<: *default_replica
    variables:
        statement_timeout: 60s
        lock_timeout: 55s
