development:
  tg_bot_token: "5905765496:AAFd6lwrhqmAePskQDsnfWwUmspr-SIHjNU"
  chatgpt_token: "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"


# https://api.telegram.org/bot5905765496:AAFd6lwrhqmAePskQDsnfWwUmspr-SIHjNU/setWebhook?url=https://268d-94-43-143-69.eu.ngrok.io/telegram
  #  https://268d-94-43-143-69.eu.ngrok.io